# Generated by Django 3.2.8 on 2021-11-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.academy')),
            ],
        ),
    ]
