# Generated by Django 3.2.8 on 2021-11-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tb_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_student',
            new_name='Student',
        ),
    ]
